order:
  pay-timeout-seconds: 60 # 订单支付超时时长，单位：秒。
  create-frequency-seconds: 480 # 订单创建频率，单位：秒

logging:
  level:
    cn.iocoder.springcloud.labx12.userapplication.controller.DemoController: DEBUG

test: true

#xx-password: '{cipher}5fca0df4439ee4b2830195555934985442efee67fe1e4bb4cce6fde2ff081a10'
yy-password: '{cipher}AQCl9dA/CSkWrtWlRxkjUP7GwTwkgs0lN3zC8gbpeufLZQ89IeaIqj90Bo5g36IGtR2O7w9idzOA1TACGW+RNhpv4GHWgO6+7vVPX/wo+4Wm1me9McnVLREhg9J+c+SIPNPYEPV+wliPon/K5Dl5bUP9CiWPE7IFNDegAN9w5DELb8i6OM2z736X8zqBePpv1s2zt0D5RhxEFgV1gnJ9cJHK6XImC9im5FqF5zKwmjJrHe7rBdFrzqPT1b1gzyrxk0MxtIYPXzfZT89xvBqul9tUP/V/rI4RXZEfcClz5t+ahgFTh6wERjTztlEnA2e86EODOkR42/2hi/HUyCcqG4WSU+K1aJ0q15JLEORvLFbZKvZZ/ifyk/OKaW8vUdJ1uko='
